<?php

function caesarcipher_menu() {
    $items['caesarcipher'] = array(
        'title' => 'Encode a message below',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('caesarcipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['caesarcipher_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'caesarcipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function caesarcipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter an integer to shift it by that many spaces'),
        '#element_validate' => array('element_validate_value'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter either left or right'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter a word or phrase'),
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Scramble your phrase!',
    );
    return $form;
}

function element_validate_value($form, &$form_state) {
    $value = $form_state['values']['shift_value'];
    if (!preg_match('/^[0-9]*$/', $value)) {
        form_set_error('shift_value', t('Your input must ONLY contain only numbers smaller than 2600000000000000000'));
    }
}

function element_validate_direction($element) {
    if ((strtolower($element['#value']) != 'left') && (strtolower($element['#value']) != 'right')) {
        form_error($element, t('Please enter ONLY the values left or right.'));
    }
}

function element_validate_phrase($form, &$form_state) {
    $phrase = strtolower($form_state['values']['phrase']);
    if (!preg_match('/^[a-zA-Z0-9,"  *".!?@#$%& ]*$/', $phrase)) {
        form_set_error('shift_phrase', t('Your input must ONLY contain letters, numbers, and the following characters: ,!?.'));
    }
}



function caesarcipher_form_submit($form, &$form_state) {

    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g',
    'h', 'i', 'j', 'k', 'l', 'm', 'n',
    'o', 'p', 'q', 'r', 's', 't',
    'u', 'v', 'w', 'x', 'y', 'z');

    $numbers = array_flip($alphabet);
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = strtolower($form_state['values']['phrase']);
    $maximum = 2600000000000000000;
    $phrase_array = str_split($phrase);
    $phrase_flip = array_flip($phrase_array);
    $phrase_length = count($phrase_array);
    $array = array();

    if ($direction === 'right') {
        for ($i=0; $i<$phrase_length; $i++) {

            if ($phrase_array[$i] === 'a' || $phrase_array[$i] === 'b' || $phrase_array[$i] === 'c'
            || $phrase_array[$i] === 'd' || $phrase_array[$i] === 'e' || $phrase_array[$i] === 'f' || $phrase_array[$i] === 'g' || $phrase_array[$i] === 'h' || $phrase_array[$i] === 'i'
            || $phrase_array[$i] === 'j' || $phrase_array[$i] === 'k' || $phrase_array[$i] === 'l' || $phrase_array[$i] === 'm' || $phrase_array[$i] === 'n' || $phrase_array[$i] === 'o'
            || $phrase_array[$i] === 'p' || $phrase_array[$i] === 'q' || $phrase_array[$i] === 'r' || $phrase_array[$i] === 's' || $phrase_array[$i] === 't' || $phrase_array[$i] === 'u'
            || $phrase_array[$i] === 'v' || $phrase_array[$i] === 'w' || $phrase_array[$i] === 'x' || $phrase_array[$i] === 'y' || $phrase_array[$i] === 'z') {

            $result = $alphabet[(($numbers[$phrase_array[$i]]+$shift_value) + $maximum) % 26];
            }  else {
                $result = $phrase_array[$i];

            }
            array_push($array, $result);
        }
    }
    else  {
        for ($i=0; $i<$phrase_length; $i++) {

            if ($phrase_array[$i] === 'a' || $phrase_array[$i] === 'b' || $phrase_array[$i] === 'c'
            || $phrase_array[$i] === 'd' || $phrase_array[$i] === 'e' || $phrase_array[$i] === 'f' || $phrase_array[$i] === 'g' || $phrase_array[$i] === 'h' || $phrase_array[$i] === 'i'
            || $phrase_array[$i] === 'j' || $phrase_array[$i] === 'k' || $phrase_array[$i] === 'l' || $phrase_array[$i] === 'm' || $phrase_array[$i] === 'n' || $phrase_array[$i] === 'o'
            || $phrase_array[$i] === 'p' || $phrase_array[$i] === 'q' || $phrase_array[$i] === 'r' || $phrase_array[$i] === 's' || $phrase_array[$i] === 't' || $phrase_array[$i] === 'u'
            || $phrase_array[$i] === 'v' || $phrase_array[$i] === 'w' || $phrase_array[$i] === 'x' || $phrase_array[$i] === 'y' || $phrase_array[$i] === 'z') {

            $result = $alphabet[(($numbers[$phrase_array[$i]]-$shift_value) + $maximum) % 26];
        }  else {
            $result = $phrase_array[$i];

            }
            array_push($array, $result);
        }
    }
    $answer = implode("", $array);

    $_SESSION['answer'] = $answer;
    $form_state['redirect'] = 'caesarcipher_success_page';
}


function caesarcipher_success() {
       $answer = $_SESSION['answer'];
       return '<h1>Here is your incoded input:' . $answer . '</h1>';
}
