<?php

function caesarcipher_menu() {
    $items['caesarcipher'] = array(
        'title' => 'Encode a message below',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('caesarcipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['caesarcipher_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'caesarcipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function caesarcipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter an integer to shift it by that many spaces'),
        '#element_validate' => array('element_validate_value'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Please enter queens Y-coordinate'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Please enter a word or phrase'),
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Scramble your phrase!',
    );
    return $form;
}

function element_validate_value($form, &$form_state) {
    $value = $form_state['values']['shift_value'];
    if (!preg_match('/^[0-9]*$/', $value)) {
        form_set_error('shift_value', t('Your input must ONLY contain letters, numbers, and the following characters: ,!?.'));
    }
}

function element_validate_direction($element) {
    if ((strtolower($element['#value']) != 'left') && (strtolower($element['#value']) != 'right')) {
        form_error($element, t('Please enter ONLY the values left or right.'));
    }
}

function element_validate_phrase($form, &$form_state) {
    $shift_phrase = strtolower($form_state['values']['shift_phrase']);
    if (!preg_match('/^[a-zA-Z0-9,.!? ]*$/', $shift_phrase)) {
        form_set_error('shift_phrase', t('Your input must ONLY contain letters, numbers, and the following characters: ,!?.'));
    }
}



function caesarcipher_form_submit($form, &$form_state) {

    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g',
    'h', 'i', 'j', 'k', 'l', 'm', 'n',
    'o', 'p', 'q', 'r', 's', 't',
    'u', 'v', 'w', 'x', 'y', 'z');

    $numbers = array_flip($alphabet);
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['shift_direction'];
    $phrase = $form_state['values']['phrase'];
    $phrase_array = str_split($phrase);
    $phrase_flip = array_flip($phrase_array);
    $phrase_length = count($phrase_array);
    $answer = '';

    if ($direction === 'right') {
        for ($i=0; $i<$phrase_length; $i++) {
            $answer .= $alphabet[($numbers[$phrase_array[$i]]+$shift_value) % 26];
        }
    }
    else {
        for ($i=0; $i<$phrase_length; $i++) {
        $answer .= $alphabet[($numbers[$phrase_array[$i]]-$shift_value) % 26];
        }
    }

    $_SESSION['answer'] = $answer;
    $form_state['redirect'] = 'caesarcipher_success_page';
}


function caesarcipher_success() {
       $answer = $_SESSION['answer'];
       return '<h1>Here is your incoded input:' . $answer . '</h1>';
}

//Sudo code answer(shift right):
// - create an assoc array where key is letter and value is number
// - use modulo to reduce to remainder
// for each letter, return value that coorespondes with key, store in a variable,
// add shift value to each
    // if  that total value is <= 25, return key
    //else subtract 26 from that value, and return that key.
//(shift left)
//if total value is less than 0, add that value (a negative number) to 26, or subtract it's absolute value from 26.Then add 1.  Then return that key.

//characters
    //if x does not equal a-z, return x.
